FROM hashicorp/terraform:latest

RUN apk add --no-cache bash curl python3 py3-pip && \
    pip3 install --upgrade pip --break-system-packages && \
    pip3 install azure-cli --break-system-packages

WORKDIR /workspace
